#pragma once

#include "NativeGameplayTags.h"

namespace MyGameplayTags
{
	/** Input Tags **/
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

	/** Player Tags **/
	
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);

	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);

	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);

	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Blocked);



	/** Enemy tags **/

	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);

	/** Shared tags **/
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	MAV_BOSSFIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
}
